# Configuration file for Bandit, a security linter for Python code

# List of tests to skip during analysis
skips:
  # Add specific test IDs to skip here

# Directories to exclude from analysis
exclude_dirs:
  - "private"
